name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ansible-galaxy version
        run: ansible-galaxy --version

      - name: Get version from GITHUB_REF
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Ansible collection
        run: ansible-galaxy collection build

      - name: Publish collection
        run: ansible-galaxy collection publish --token ${ANSIBLE_GALAXY_API_KEY} ./haxorof-virtualization-${{ steps.get_version.outputs.VERSION }}.tar.gz
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            See changelog [here](https://github.com/haxorof/ansible-collection-virtualization/blob/${{ steps.get_version.outputs.VERSION }}/CHANGELOG.md)
          draft: false
          prerelease: false
